# Generated by Django 5.0.6 on 2024-05-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('top_header', models.TextField()),
                ('content_header_1', models.TextField()),
                ('content_header_2', models.TextField()),
                ('content_header_3', models.TextField()),
                ('content_header_4', models.TextField()),
                ('content_text_1', models.TextField()),
                ('content_text_2', models.TextField()),
                ('content_text_3', models.TextField()),
                ('content_text_4', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='help',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
