# Generated by Django 5.0.6 on 2024-05-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_service_alter_contact_help_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='title_slug',
            field=models.SlugField(default='demo', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
