# Generated by Django 5.0.6 on 2024-05-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_service_title_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
